# Generated by Django 4.2.4 on 2023-08-20 12:35

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag_path', models.CharField(blank=True, max_length=500)),
                ('ease_of_biz', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[api.models.non_negative_validator])),
                ('gdp', models.BigIntegerField(blank=True, null=True, validators=[api.models.non_negative_validator])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.CharField(choices=[('kg', 'Kilograms'), ('MT', 'Metric Ton'), ('1000 MT', '1000 Metric Tons'), ('1 M. MT', '1 Million Metric Tons'), ('$ M.', 'Million Dollars'), ('MCM', 'Milion Cubic Meters'), ('Mct', 'Million Carats'), ('Kct', 'Thousands of Carats')], max_length=50)),
                ('amount', models.CharField(max_length=25)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.CharField(choices=[('kg', 'Kilograms'), ('MT', 'Metric Ton'), ('1000 MT', '1000 Metric Tons'), ('1 M. MT', '1 Million Metric Tons'), ('$ M.', 'Million Dollars'), ('MCM', 'Milion Cubic Meters'), ('Mct', 'Million Carats'), ('Kct', 'Thousands of Carats')], max_length=50)),
                ('amount', models.CharField(max_length=25)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25, validators=[api.models.non_negative_validator])),
                ('share', models.DecimalField(decimal_places=10, max_digits=13, validators=[api.models.non_negative_validator])),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='GovInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('prod_and_use', models.TextField()),
                ('recycling', models.TextField()),
                ('events', models.TextField()),
                ('world_resources', models.TextField()),
                ('substitutes', models.TextField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25, validators=[api.models.non_negative_validator])),
                ('share', models.DecimalField(decimal_places=10, max_digits=13, validators=[api.models.non_negative_validator])),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=13, validators=[api.models.non_negative_validator])),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reserves',
            constraint=models.UniqueConstraint(fields=('year', 'country', 'commodity'), name='unique_reserves_year_country_commodity'),
        ),
        migrations.AddConstraint(
            model_name='production',
            constraint=models.UniqueConstraint(fields=('year', 'country', 'commodity'), name='unique_production_year_country_commodity'),
        ),
        migrations.AddConstraint(
            model_name='importdata',
            constraint=models.UniqueConstraint(fields=('year', 'country', 'commodity'), name='unique_import_year_country_commodity'),
        ),
        migrations.AddIndex(
            model_name='govinfo',
            index=models.Index(fields=['year', 'commodity'], name='api_govinfo_year_1577aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='govinfo',
            constraint=models.UniqueConstraint(fields=('year', 'commodity'), name='unique_year_commodity'),
        ),
        migrations.AddConstraint(
            model_name='exportdata',
            constraint=models.UniqueConstraint(fields=('year', 'country', 'commodity'), name='unique_export_year_country_commodity'),
        ),
        migrations.AddIndex(
            model_name='commodityprice',
            index=models.Index(fields=['commodity'], name='api_commodi_commodi_43544a_idx'),
        ),
        migrations.AddConstraint(
            model_name='commodityprice',
            constraint=models.UniqueConstraint(fields=('commodity', 'date'), name='unique_commodity_date'),
        ),
    ]
