# Generated by Django 4.2.4 on 2023-08-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='income_group',
            field=models.CharField(blank=True, choices=[('High income', 'High income'), ('Upper middle income', 'Upper middle income'), ('Lower middle income', 'Lower middle income'), ('Low income', 'Low income')], max_length=50, null=True),
        ),
    ]
