# Generated by Django 4.2.4 on 2023-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_income_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityprice',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
