# Generated by Django 4.2.4 on 2023-08-28 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_commodityprice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='commodity',
            name='img_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
