# Generated by Django 4.2.4 on 2023-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commodity_companies_commodity_img_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
