# Generated by Django 4.2.4 on 2023-09-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_country_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvardCountry',
            fields=[
                ('harvard_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='HarvardCommodity',
            fields=[
                ('harvard_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commodity')),
            ],
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.harvardcommodity'),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.harvardcountry'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.harvardcommodity'),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.harvardcountry'),
        ),
    ]
