# Generated by Django 4.2.4 on 2023-09-18 17:50

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_harvardcountry_harvardcommodity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('total_imports', models.DecimalField(decimal_places=10, max_digits=30, validators=[api.models.non_negative_validator])),
                ('total_exports', models.DecimalField(decimal_places=10, max_digits=30, validators=[api.models.non_negative_validator])),
                ('total_commodity_imports', models.DecimalField(decimal_places=10, max_digits=30, validators=[api.models.non_negative_validator])),
                ('total_commodity_exports', models.DecimalField(decimal_places=10, max_digits=30, validators=[api.models.non_negative_validator])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importexportbalance',
            constraint=models.UniqueConstraint(fields=('year', 'country'), name='unique_year_country_balance'),
        ),
    ]
