# Generated by Django 4.2.4 on 2023-09-19 19:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_importexportbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, validators=[api.models.non_negative_validator]),
        ),
        migrations.AddField(
            model_name='reserves',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserves',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, validators=[api.models.non_negative_validator]),
        ),
    ]
